import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'

const smokeSource = await readFile(new URL('./agent-bridge-browser-smoke.mjs', import.meta.url), 'utf8')
const harnessSource = await readFile(new URL('./helpers/agent-bridge-browser-smoke-harness.mjs', import.meta.url), 'utf8')
const e2eReport = await readFile(new URL('../docs/reviews/CR-AGENT-BRIDGE-E2E-2026-05-22.md', import.meta.url), 'utf8')
const completionAudit = await readFile(new URL('../docs/reviews/CR-AGENT-BRIDGE-COMPLETION-AUDIT-2026-05-24.md', import.meta.url), 'utf8')

test('browser smoke summaries do not print token prefixes', () => {
  assert.doesNotMatch(smokeSource, /\bapiTokenPrefix\b/)
  assert.doesNotMatch(smokeSource, /\bbridgeTokenPrefix\b/)
  assert.doesNotMatch(smokeSource, /\btokenPrefix\b/)
  assert.doesNotMatch(harnessSource, /\btokenPrefix\b/)
  assertNoReportTokenPrefix(e2eReport)
  assertNoReportTokenPrefix(completionAudit)
  assert.match(smokeSource, /\bapiTokenPresent: Boolean\(/)
  assert.match(e2eReport, /\bapiTokenPresent = true\b/)
})

test('current reports separate public complex-site proof from default policy proof', () => {
  const e2eCurrentSummary = sectionBetween(e2eReport, 'This report is no longer', '## Current Verification')
  const e2eCurrentVerification = sectionBetween(e2eReport, '## Current Verification', '## Browser Smoke')
  const latestSmoke = sectionBetween(e2eReport, 'Latest successful smoke:', '## Remaining Risks')
  const task10Matrix = sectionBetween(completionAudit, 'Task 10 当前共有', '## Verification Run')

  assert.doesNotMatch(e2eCurrentSummary, /live-browser smoke covers `https:\/\/example\.com`/)
  assert.doesNotMatch(e2eCurrentVerification, /Enabled captures completed for `https:\/\/example\.com`/)
  assert.doesNotMatch(latestSmoke, /Capture targets: `https:\/\/example\.com`/)
  assert.doesNotMatch(latestSmoke, /Public target assertions: final URL was `https:\/\/example\.com\/`/)
  assert.doesNotMatch(task10Matrix, /Chrome for Testing smoke 覆盖 `https:\/\/example\.com`/)
  assert.doesNotMatch(task10Matrix, /public complex-site gap remains/)

  assert.match(e2eCurrentSummary, /separate public complex-site capture for `https:\/\/www\.wikipedia\.org\/`/)
  assert.match(e2eCurrentVerification, /public-complex-target/)
  assert.match(e2eCurrentVerification, /198\.18\.0\.19/)
  assert.match(latestSmoke, /Public target status: counted only through the explicit `public-complex-target` scenario/)
  assert.match(latestSmoke, /privateNetworkOverrideUsed = true/)
  assert.match(task10Matrix, /Proven locally with explicit DNS-proxy caveat/)
  assert.match(smokeSource, /runPublicComplexTargetScenario/)
  assert.match(smokeSource, /privateNetworkOverrideUsed: true/)
})

test('current reports keep incognito live metadata branch unproven', () => {
  const e2eRemainingRisks = sectionFrom(e2eReport, '## Remaining Risks')
  const e2eAdditionalChecks = sectionBetween(e2eReport, 'Additional focused checks recorded for this slice:', 'Environment note:')
  const task10Matrix = sectionBetween(completionAudit, '| Target policy and target failures', '| Profile privacy and transfer')
  const currentStatus = sectionFrom(completionAudit, '## Current Status')

  assert.match(smokeSource, /runIncognitoWindowBridgeProbeScenario/)
  assert.match(smokeSource, /environment-skip-incognito-window-extension-not-connected/)
  assert.match(e2eRemainingRisks, /incognito-window-bridge-probe/)
  assert.match(e2eRemainingRisks, /failed as `EXTENSION_NOT_CONNECTED`/)
  assert.match(e2eRemainingRisks, /Incognito live metadata rejection is still not fully run/)
  assert.match(e2eRemainingRisks, /exact live incognito `INCOGNITO_NOT_SUPPORTED` browser metadata rejection/)
  assert.match(e2eRemainingRisks, /chrome\.extension\.inIncognitoContext === true/)
  assert.match(e2eRemainingRisks, /posts `INCOGNITO_NOT_SUPPORTED` before loading `\/request`/)
  assert.match(e2eAdditionalChecks, /content incognito context follow-up/)
  assert.match(e2eAdditionalChecks, /PROFILE_TRANSPORT_FAILED/)
  assert.match(e2eAdditionalChecks, /failed \/ INCOGNITO_NOT_SUPPORTED/)
  assert.match(task10Matrix, /`--incognito` 窗口路径 probe 也未加载扩展 content script/)
  assert.match(task10Matrix, /chrome\.extension\.inIncognitoContext === true/)
  assert.match(task10Matrix, /INCOGNITO_NOT_SUPPORTED/)
  assert.match(currentStatus, /content client 已有 `chrome\.extension\.inIncognitoContext` 单元契约/)
  assert.doesNotMatch(currentStatus, /精确 incognito `INCOGNITO_NOT_SUPPORTED` 浏览器元数据路径.*已完成/)
})

test('current verification records the latest unit test count', () => {
  const e2eCurrentVerification = sectionBetween(e2eReport, '## Current Verification', '## Browser Smoke')
  const task10Matrix = sectionBetween(completionAudit, 'Task 10 当前共有', '## Verification Run')

  assert.doesNotMatch(e2eCurrentVerification, /175 tests passed, 0 failed/)
  assert.match(e2eCurrentVerification, /2026-05-26/)
  assert.doesNotMatch(e2eCurrentVerification, /198 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /199 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /202 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /203 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /204 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /205 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /206 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /207 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /208 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /209 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /210 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /211 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /212 tests passed, 0 failed/)
  assert.doesNotMatch(e2eCurrentVerification, /213 tests passed, 0 failed/)
  assert.match(e2eCurrentVerification, /219 tests passed, 0 failed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 180 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 198 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 199 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 202 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 203 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 204 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 205 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 206 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 207 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 208 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 209 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 210 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 211 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 212 tests passed/)
  assert.doesNotMatch(task10Matrix, /最新 `pnpm run test:unit` 为 213 tests passed/)
  assert.match(task10Matrix, /最新 `pnpm run test:unit` 为 219 tests passed/)
})

test('current reports include fresh lint and typecheck gate evidence', () => {
  const e2eCurrentVerification = sectionBetween(e2eReport, '## Current Verification', '## Browser Smoke')
  const verificationRun = sectionBetween(completionAudit, '## Verification Run', '## Current Status')

  assert.match(e2eCurrentVerification, /\| `pnpm run lint`[\s\S]*2026-05-26/)
  assert.match(e2eCurrentVerification, /\| `pnpm run typecheck`[\s\S]*2026-05-26/)
  assert.match(e2eCurrentVerification, /rate-limit smoke\/report follow-up/)
  assert.match(e2eCurrentVerification, /vue-tsc --noEmit/)
  assert.match(e2eCurrentVerification, /production build/)
  assert.match(e2eCurrentVerification, /dist\/manifest\.json/)
  assert.match(verificationRun, /追加 active-tab unavailable smoke\/report follow-up 后重新执行 `pnpm run lint`：通过/)
  assert.match(verificationRun, /追加 active-tab unavailable smoke\/report follow-up 后重新执行 `pnpm run typecheck`：通过/)
  assert.match(verificationRun, /追加 rate-limit smoke\/report follow-up 后重新执行 `pnpm run lint`：通过/)
  assert.match(verificationRun, /追加 rate-limit smoke\/report follow-up 后重新执行 `pnpm run typecheck`：通过/)
  assert.match(verificationRun, /重新生成 injected IIFE 与 `dist\/manifest\.json`/)
})

test('current reports include live result-expiry bridge page evidence', () => {
  const e2eAdditionalChecks = sectionBetween(e2eReport, 'Additional focused checks recorded for this slice:', 'Environment note:')
  const e2eRemainingRisks = sectionFrom(e2eReport, '## Remaining Risks')
  const task10Matrix = sectionBetween(completionAudit, '| 终态、并发和取消语义', '| HTTP resource pressure')
  const currentStatus = sectionFrom(completionAudit, '## Current Status')

  assert.match(smokeSource, /runResultExpiryBridgePageScenario/)
  assert.match(smokeSource, /result-expiry-bridge-page/)
  assert.match(e2eAdditionalChecks, /STACKPRISM_BROWSER_SMOKE_SCENARIO=result-expiry-bridge-page/)
  assert.match(e2eAdditionalChecks, /410 \/ CAPTURE_RESULT_EXPIRED/)
  assert.match(e2eAdditionalChecks, /did not contain bridge token material/)
  assert.match(e2eRemainingRisks, /Completed-result expiry is also covered by `result-expiry-bridge-page` live Chrome smoke/)
  assert.doesNotMatch(e2eRemainingRisks, /Expired bridge page token suppression remains covered by JS\/Python automated bridge tests/)
  assert.match(task10Matrix, /completed result TTL 过期后 profile endpoint 和 `\/bridge` 均返回 `CAPTURE_RESULT_EXPIRED`/)
  assert.match(currentStatus, /result expiry bridge page smoke/)
})

test('current reports include focused bridge self-target smoke evidence', () => {
  const e2eAdditionalChecks = sectionBetween(e2eReport, 'Additional focused checks recorded for this slice:', 'Environment note:')
  const targetPolicyRow = sectionBetween(completionAudit, '| Target policy and target failures', '| Profile privacy and transfer')
  const currentStatus = sectionFrom(completionAudit, '## Current Status')

  assert.match(smokeSource, /runBridgeSelfTargetBlockedScenario/)
  assert.match(smokeSource, /bridge-self-target-blocked/)
  assert.match(e2eAdditionalChecks, /STACKPRISM_BROWSER_SMOKE_SCENARIO=bridge-self-target-blocked/)
  assert.match(e2eAdditionalChecks, /400 \/ BRIDGE_SELF_TARGET_BLOCKED/)
  assert.match(e2eAdditionalChecks, /`localhost` loopback alias/)
  assert.match(e2eAdditionalChecks, /\/health\.activeCaptures` remained 0/)
  assert.match(targetPolicyRow, /`bridge-self-target-blocked`/)
  assert.match(targetPolicyRow, /当前 bridge origin 和 `localhost` alias/)
  assert.doesNotMatch(targetPolicyRow, /self-target guard/)
  assert.match(currentStatus, /bridge self-target smoke/)
  assert.match(currentStatus, /bridge-origin 初始目标拒绝/)
})

test('current reports include live active-tab unavailable evidence', () => {
  const e2eAdditionalChecks = sectionBetween(e2eReport, 'Additional focused checks recorded for this slice:', 'Environment note:')
  const targetPolicyRow = sectionBetween(completionAudit, '| Target policy and target failures', '| Profile privacy and transfer')
  const currentStatus = sectionFrom(completionAudit, '## Current Status')

  assert.match(smokeSource, /runActiveTabUnavailableScenario/)
  assert.match(smokeSource, /active-tab-unavailable/)
  assert.match(e2eAdditionalChecks, /STACKPRISM_BROWSER_SMOKE_SCENARIO=active-tab-unavailable/)
  assert.match(e2eAdditionalChecks, /ACTIVE_TAB_UNAVAILABLE/)
  assert.match(e2eAdditionalChecks, /profile read returned 409/)
  assert.match(e2eAdditionalChecks, /target probe received 0 requests/)
  assert.match(e2eAdditionalChecks, /no target URL tab was opened/)
  assert.match(targetPolicyRow, /`active-tab-unavailable`/)
  assert.match(targetPolicyRow, /target request count 0/)
  assert.match(currentStatus, /active-tab unavailable smoke/)
  assert.match(currentStatus, /active-tab 缺失 fail-closed/)
})

test('current reports include target-mode query and keep-tab-open smoke evidence', () => {
  const e2eFollowUps = sectionBetween(
    e2eReport,
    '2026-05-25 targetMode query live smoke follow-up',
    '2026-05-25 sequential capture pressure'
  )
  const task10Matrix = sectionBetween(completionAudit, '| Target policy and target failures', '| Profile privacy and transfer')

  assert.match(smokeSource, /target-mode-query-boundaries/)
  assert.match(smokeSource, /keepTabOpenWasTrue/)
  assert.match(smokeSource, /keptNewTargetTabId/)
  assert.match(e2eFollowUps, /STACKPRISM_BROWSER_SMOKE_SCENARIO=target-mode-query-boundaries/)
  assert.match(e2eFollowUps, /keepTabOpen=true/)
  assert.match(e2eFollowUps, /keptNewTargetTabId/)
  assert.match(task10Matrix, /targetMode query live smoke/)
  assert.match(task10Matrix, /keepTabOpen=true/)
  assert.match(task10Matrix, /保留插件新建目标 tab/)
})

test('current reports include live request-shell rejection smoke evidence', () => {
  const e2eAdditionalChecks = sectionBetween(e2eReport, 'Additional focused checks recorded for this slice:', 'Environment note:')
  const resourcePressureRow = sectionBetween(completionAudit, '| HTTP resource pressure', '| Service worker / extension lifecycle')

  assert.match(smokeSource, /runRequestShellRejectionsScenario/)
  assert.match(smokeSource, /request-shell-rejections/)
  assert.match(smokeSource, /rejectedCases/)
  assert.match(smokeSource, /duplicateContentType/)
  assert.match(smokeSource, /duplicateContentLength/)
  assert.match(smokeSource, /invalidContentLength/)
  assert.match(smokeSource, /unsupportedCharset/)
  assert.match(e2eAdditionalChecks, /STACKPRISM_BROWSER_SMOKE_SCENARIO=request-shell-rejections/)
  assert.match(e2eAdditionalChecks, /19 类原始 request-shell/)
  assert.match(e2eAdditionalChecks, /duplicate Content-Type/)
  assert.match(e2eAdditionalChecks, /invalid Content-Length/)
  assert.match(e2eAdditionalChecks, /target request count 0/)
  assert.match(e2eAdditionalChecks, /healthAfterRejections/)
  assert.match(resourcePressureRow, /request-shell-rejections/)
  assert.match(resourcePressureRow, /19 类原始 request-shell/)
  assert.match(resourcePressureRow, /拒绝后 `\/health` 恢复 200/)
})

test('current reports include live keep-alive timeout evidence', () => {
  const e2eFollowUps = sectionBetween(e2eReport, '2026-05-25 resource timeouts smoke follow-up', '2026-05-25 release workflow gate')
  const resourcePressureRow = sectionBetween(completionAudit, '| HTTP resource pressure', '| Service worker / extension lifecycle')
  const verificationRun = sectionBetween(completionAudit, '## Verification Run', '## Current Status')

  assert.match(smokeSource, /probeKeepAliveIdleClose/)
  assert.match(smokeSource, /afterKeepAliveIdleStatusLine/)
  assert.match(e2eFollowUps, /STACKPRISM_BROWSER_SMOKE_SCENARIO=resource-timeouts/)
  assert.match(e2eFollowUps, /default idle window/)
  assert.match(e2eFollowUps, /subsequent `\/health` request returned 200/)
  assert.match(resourcePressureRow, /默认 idle 窗口/)
  assert.match(verificationRun, /STACKPRISM_BROWSER_SMOKE_SCENARIO=resource-timeouts STACKPRISM_BROWSER_SMOKE_CDP_PORT=9561/)
})

test('current reports include live default rate-limit evidence', () => {
  const e2eFollowUps = sectionBetween(
    e2eReport,
    '2026-05-26 rate-limit smoke follow-up',
    '2026-05-26 target URL validation smoke follow-up'
  )
  const bridgeApiRow = sectionBetween(completionAudit, '| Bridge API semantics and rate limiting', '| Bridge 启动与环境错误')
  const verificationRun = sectionBetween(completionAudit, '## Verification Run', '## Current Status')

  assert.match(smokeSource, /runRateLimitScenario/)
  assert.match(smokeSource, /runProfileRateLimitScenario/)
  assert.match(smokeSource, /rate-limit/)
  assert.match(smokeSource, /profile-rate-limit/)
  assert.match(smokeSource, /createRateLimit/)
  assert.match(smokeSource, /queryRateLimit/)
  assert.match(smokeSource, /profileRateLimit/)
  assert.match(e2eFollowUps, /STACKPRISM_BROWSER_SMOKE_SCENARIO=rate-limit/)
  assert.match(e2eFollowUps, /STACKPRISM_BROWSER_SMOKE_SCENARIO=profile-rate-limit/)
  assert.match(e2eFollowUps, /11th create request returned `429 \/ RATE_LIMITED`/)
  assert.match(e2eFollowUps, /121st status read returned `429 \/ RATE_LIMITED`/)
  assert.match(e2eFollowUps, /121st profile read returned `429 \/ RATE_LIMITED`/)
  assert.match(e2eFollowUps, /target request count was 0/)
  assert.match(bridgeApiRow, /`rate-limit`/)
  assert.match(bridgeApiRow, /`profile-rate-limit`/)
  assert.match(bridgeApiRow, /默认 create limit 10/)
  assert.match(bridgeApiRow, /默认 query limit 120/)
  assert.match(bridgeApiRow, /120 次 profile reads/)
  assert.match(verificationRun, /STACKPRISM_BROWSER_SMOKE_SCENARIO=rate-limit STACKPRISM_BROWSER_SMOKE_CDP_PORT=9562/)
  assert.match(verificationRun, /STACKPRISM_BROWSER_SMOKE_SCENARIO=profile-rate-limit STACKPRISM_BROWSER_SMOKE_CDP_PORT=9564/)
})

test('current reports include live target URL validation evidence', () => {
  const e2eFollowUps = sectionBetween(e2eReport, '2026-05-26 target URL validation smoke follow-up', 'Environment note:')
  const targetPolicyRow = sectionBetween(completionAudit, '| Target policy and target failures', '| Profile privacy and transfer')
  const verificationRun = sectionBetween(completionAudit, '## Verification Run', '## Current Status')

  assert.match(smokeSource, /runTargetUrlValidationScenario/)
  assert.match(smokeSource, /target-url-validation/)
  assert.match(smokeSource, /unsupportedProtocol/)
  assert.match(smokeSource, /credentialUrl/)
  assert.match(smokeSource, /loopbackPrivateTarget/)
  assert.match(smokeSource, /bridgeSelfTarget/)
  assert.match(e2eFollowUps, /STACKPRISM_BROWSER_SMOKE_SCENARIO=target-url-validation/)
  assert.match(e2eFollowUps, /unsupported protocol/)
  assert.match(e2eFollowUps, /credential URL/)
  assert.match(e2eFollowUps, /loopback private target/)
  assert.match(e2eFollowUps, /bridge self-target/)
  assert.match(e2eFollowUps, /activeCaptures = 0/)
  assert.match(e2eFollowUps, /target request count was 0/)
  assert.match(targetPolicyRow, /`target-url-validation`/)
  assert.match(targetPolicyRow, /unsupported protocol/)
  assert.match(targetPolicyRow, /credential URL/)
  assert.match(targetPolicyRow, /loopback private target/)
  assert.match(targetPolicyRow, /bridge self-target/)
  assert.match(verificationRun, /STACKPRISM_BROWSER_SMOKE_SCENARIO=target-url-validation STACKPRISM_BROWSER_SMOKE_CDP_PORT=9563/)
})

test('completion audit records current worktree hygiene counts', () => {
  const currentStatus = sectionFrom(completionAudit, '## Current Status')

  assert.doesNotMatch(currentStatus, /47 个 unstaged 文件/)
  assert.match(currentStatus, /52 个 staged 文件/)
  assert.match(currentStatus, /39 个 unstaged 文件/)
  assert.match(currentStatus, /4 个 untracked Agent Bridge 文件/)
})

const assertNoReportTokenPrefix = source => {
  assert.doesNotMatch(source, /apiTokenPrefix\s*=\s*"spb_/)
  assert.doesNotMatch(source, /bridgeTokenPrefix\s*=\s*"spbt_/)
  assert.doesNotMatch(source, /把 `spb_`/)
  assert.doesNotMatch(source, /把 `spbt_`/)
  assert.doesNotMatch(source, /`spb_`\/`spbt_` token/)
  assert.doesNotMatch(source, /`spb_` token/)
  assert.doesNotMatch(source, /`spbt_` token/)
  assert.doesNotMatch(source, /records only the extension id and token prefix/)
}

const sectionBetween = (source, start, end) => {
  const startIndex = source.indexOf(start)
  assert.notEqual(startIndex, -1, `Missing section start: ${start}`)
  const endIndex = source.indexOf(end, startIndex)
  assert.notEqual(endIndex, -1, `Missing section end: ${end}`)
  return source.slice(startIndex, endIndex)
}

const sectionFrom = (source, start) => {
  const startIndex = source.indexOf(start)
  assert.notEqual(startIndex, -1, `Missing section start: ${start}`)
  return source.slice(startIndex)
}
